### ISSUE TITLE
Object.assign support

### ISSUE THREAD

**Issue by pi0** [egoist/babel-preset-vue-app#1]
Hi. This is following to a report in nuxt/nuxt.js#463 . According to [index.js:16](https://github.com/vuejs/babel-preset-vue-app/blob/master/index.js#L16) we are targeting IE+9. 
But as [indicated here](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign) Object assign is not supported in many environments including : 
**IE**: ... 11
**Android**: .... 4.4, 5.0, 5.1
**IOS**: ... 8, 9

Isn't this a big miss? We already have regenerator runtime and adding another lightweight transform would add vue.js support for many many devices. @egoist What is your idea about that?

**Comment by egoist** [comment]
Guess we should add `Object.assign = require('object-assign')` to README

**Comment by pi0** [comment]
@egoist So Object.assign transform would not be added by preset itself & this require additional steps in other projects like Nuxt. am i right? :))

**Comment by egoist** [comment]
Yes, it requires a polyfill anyways according to what I knew.

**Comment by pi0** [comment]
@egoist We also have [transform-object-assign](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-object-assign) which can bring it out of the box! Any hope adding this plugin? polyfill can't be customized to only ship this only feature and this is the only thing we want from it :))
