### ISSUE TITLE
babel-node

### ISSUE THREAD

**Issue by dunkfordyce** [egoist/babel-preset-vue-app#18]
Iv used vue-cli 3 to set up a project and I want to run some scripts manually with babel-node. My babel config is unchanged from the defaults vue-cli set. When I run my script it doesnt seem to work as expected:

```
PS D:\Projects\kuya-mc2> npx babel-node .\src\lib\data.js
npx: installed 1 in 1.565s
Path must be a string. Received undefined
D:\Projects\kuya-mc2\node_modules\@babel\node\bin\babel-node.js
D:\Projects\kuya-mc2\src\lib\data.js:1
(function (exports, require, module, __filename, __dirname) { import "core-js/modules/es6.array.iterator";
                                                              ^^^^^^
```

Any hints?

**Comment by Justineo** [comment]
You are manually running `babel-node` without anything related to Vue. I searched a little bit for you and it seems to be [an issue of `npx`](https://github.com/zkat/npx/issues/144).
