### ISSUE TITLE
Uncaught TypeError: Cannot read property 'installed' of undefined

### ISSUE THREAD

**Issue by river2333** [egoist/babel-preset-vue-app#6]
最近更新到版本1.1.1
![image](https://cloud.githubusercontent.com/assets/20136549/25220233/bc62af58-25e3-11e7-98bc-788e97dcf4f3.png)
把版本回退到0.4.0 问题就没有了

**Comment by egoist** [comment]
More details are required, maybe you're using some unsupported stage-2 features.
